In [12]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import scipy
import seaborn as sns
%matplotlib inline

In [6]:
df=pd.read_csv('creditcard.csv')
df

Time         V1         V2        V3        V4        V5  \
0            0.0  -1.359807  -0.072781  2.536347  1.378155 -0.338321   
1            0.0   1.191857   0.266151  0.166480  0.448154  0.060018   
2            1.0  -1.358354  -1.340163  1.773209  0.379780 -0.503198   
3            1.0  -0.966272  -0.185226  1.792993 -0.863291 -0.010309   
4            2.0  -1.158233   0.877737  1.548718  0.403034 -0.407193   
...          ...        ...        ...       ...       ...       ...   
284802  172786.0 -11.881118  10.071785 -9.834783 -2.066656 -5.364473   
284803  172787.0  -0.732789  -0.055080  2.035030 -0.738589  0.868229   
284804  172788.0   1.919565  -0.301254 -3.249640 -0.557828  2.630515   
284805  172788.0  -0.240440   0.530483  0.702510  0.689799 -0.377961   
284806  172792.0  -0.533413  -0.189733  0.703337 -0.506271 -0.012546   

              V6        V7        V8        V9  ...       V21       V22  \
0       0.462388  0.239599  0.098698  0.363787  ... -0.018307  0.277838   
1      -0.082361 -0.078803  0.085102 -0.255425  ... -0.225775 -0.638672   
2       1.800499  0.791461  0.247676 -1.514654  ...  0.247998  0.771679   
3       1.247203  0.237609  0.377436 -1.387024  ... -0.108300  0.005274   
4       0.095921  0.592941 -0.270533  0.817739  ... -0.009431  0.798278   
...          ...       ...       ...       ...  ...       ...       ...   
284802 -2.606837 -4.918215  7.305334  1.914428  ...  0.213454  0.111864   
284803  1.058415  0.024330  0.294869  0.584800  ...  0.214205  0.924384   
284804  3.031260 -0.296827  0.708417  0.432454  ...  0.232045  0.578229   
284805  0.623708 -0.686180  0.679145  0.392087  ...  0.265245  0.800049   
284806 -0.649617  1.577006 -0.414650  0.486180  ...  0.261057  0.643078   

             V23       V24       V25       V26       V27       V28  Amount  \
0      -0.110474  0.066928  0.128539 -0.189115  0.133558 -0.021053  149.62   
1       0.101288 -0.339846  0.167170  0.125895 -0.008983  0.014724    2.69   
2       0.909412 -0.689281 -0.327642 -0.139097 -0.055353 -0.059752  378.66   
3      -0.190321 -1.175575  0.647376 -0.221929  0.062723  0.061458  123.50   
4      -0.137458  0.141267 -0.206010  0.502292  0.219422  0.215153   69.99   
...          ...       ...       ...       ...       ...       ...     ...   
284802  1.014480 -0.509348  1.436807  0.250034  0.943651  0.823731    0.77   
284803  0.012463 -1.016226 -0.606624 -0.395255  0.068472 -0.053527   24.79   
284804 -0.037501  0.640134  0.265745 -0.087371  0.004455 -0.026561   67.88   
284805 -0.163298  0.123205 -0.569159  0.546668  0.108821  0.104533   10.00   
284806  0.376777  0.008797 -0.473649 -0.818267 -0.002415  0.013649  217.00   

        Class  
0           0  
1           0  
2           0  
3           0  
4           0  
...       ...  
284802      0  
284803      0  
284804      0  
284805      0  
284806      0  

[284807 rows x 31 columns]

In [7]:
df.isnull().sum()

Time      0
V1        0
V2        0
V3        0
V4        0
V5        0
V6        0
V7        0
V8        0
V9        0
V10       0
V11       0
V12       0
V13       0
V14       0
V15       0
V16       0
V17       0
V18       0
V19       0
V20       0
V21       0
V22       0
V23       0
V24       0
V25       0
V26       0
V27       0
V28       0
Amount    0
Class     0
dtype: int64

In [10]:
df['Class'].unique()

array([0, 1], dtype=int64)

In [20]:
df['Class'].value_counts()

Class
0    284315
1       492
Name: count, dtype: int64

### Observation

    The Target class is imbalnced 

In [21]:
X=df.drop('Class',axis=1)
y=df['Class']

In [24]:
from sklearn.model_selection import train_test_split
from sklearn.linear_model import LogisticRegression
from sklearn.model_selection import KFold,GridSearchCV
from sklearn.metrics import accuracy_score,confusion_matrix,classification_report,f1_score
import numpy as np


In [33]:
log_class=LogisticRegression()
grid={'C':10.0 **np.arange(-2,3),'penalty':['l1','l2']}
cv=KFold(n_splits=5,random_state=None,shuffle=False)

In [34]:
X_train,X_test,y_train,y_test=train_test_split(X,y,test_size=0.3,random_state=0)
X_train.shape,X_test.shape

((199364, 30), (85443, 30))

In [36]:
clf=GridSearchCV(log_class,grid,cv=cv,n_jobs=-1,scoring='f1_macro')
clf.fit(X_train,y_train)

C:\Users\z004vc9h\AppData\Local\anaconda3\Lib\site-packages\sklearn\model_selection\_validation.py:425: FitFailedWarning: 
25 fits failed out of a total of 50.
The score on these train-test partitions for these parameters will be set to nan.
If these failures are not expected, you can try to debug them by setting error_score='raise'.

Below are more details about the failures:
--------------------------------------------------------------------------------
25 fits failed with the following error:
Traceback (most recent call last):
  File "C:\Users\z004vc9h\AppData\Local\anaconda3\Lib\site-packages\sklearn\model_selection\_validation.py", line 732, in _fit_and_score
    estimator.fit(X_train, y_train, **fit_params)
  File "C:\Users\z004vc9h\AppData\Local\anaconda3\Lib\site-packages\sklearn\base.py", line 1151, in wrapper
    return fit_method(estimator, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\z004vc9h\AppData\Local\anaconda3\Lib\site-packages\

GridSearchCV(cv=KFold(n_splits=5, random_state=None, shuffle=False),
             estimator=LogisticRegression(), n_jobs=-1,
             param_grid={'C': array([1.e-02, 1.e-01, 1.e+00, 1.e+01, 1.e+02]),
                         'penalty': ['l1', 'l2']},
             scoring='f1_macro')

In [37]:
y_pred=clf.predict(X_test)
print(confusion_matrix(y_pred,y_test))
print(accuracy_score(y_pred,y_test))
print(classification_report(y_pred,y_test))

[[85253    45]
 [   43   102]]
0.9989700736163291
              precision    recall  f1-score   support

           0       1.00      1.00      1.00     85298
           1       0.69      0.70      0.70       145

    accuracy                           1.00     85443
   macro avg       0.85      0.85      0.85     85443
weighted avg       1.00      1.00      1.00     85443



### Note:- 

Focus on Precission and Recall

In [40]:
from sklearn.ensemble import RandomForestClassifier
classifier=RandomForestClassifier()
classifier.fit(X_train,y_train)
y_pred=classifier.predict(X_test)
print(confusion_matrix(y_pred,y_test))
print(accuracy_score(y_pred,y_test))
print(classification_report(y_pred,y_test))

[[85289    34]
 [    7   113]]
0.9995201479348805
              precision    recall  f1-score   support

           0       1.00      1.00      1.00     85323
           1       0.77      0.94      0.85       120

    accuracy                           1.00     85443
   macro avg       0.88      0.97      0.92     85443
weighted avg       1.00      1.00      1.00     85443



## Undersampeling

 By using undersampeling we reduce the points of maximum labels 
 
 Disadvantage :-
  Loss of Data
  
***Note***:- only do this when we have less data

In [41]:
y_train.value_counts()

Class
0    199019
1       345
Name: count, dtype: int64

In [46]:
from collections import Counter
from imblearn.under_sampling import NearMiss
ns=NearMiss(0.8)#0.8 is nothing but reducing it to 80%

X_train_ns,y_train_ns=ns.fit(X_train,y_train)
print("the number of classes before fit {}".format(Counter(y_train)))
print("the number of classes after fit {}".format(Counter(y_train_ns)))

ImportError: cannot import name '_MissingValues' from 'sklearn.utils._param_validation' (C:\Users\z004vc9h\AppData\Local\anaconda3\Lib\site-packages\sklearn\utils\_param_validation.py)

In [ ]:
classifier=RandomForestClassifier()
classifier.fit(X_train_ns,y_train_ns)

## Over Sampling

increasing the minimum class samples 

In [48]:
from imblearn.OverSampling import RandomOverSampler
os= RandomOverSampler(0.5)
X_train_ns,y_train_ns=os.fit(X_train,y_train)
print("the number of classes before fit {}".format(Counter(y_train)))
print("the number of classes after fit {}".format(Counter(y_train_ns)))


ImportError: cannot import name '_MissingValues' from 'sklearn.utils._param_validation' (C:\Users\z004vc9h\AppData\Local\anaconda3\Lib\site-packages\sklearn\utils\_param_validation.py)

In [ ]:
classifier=RandomForestClassifier()
classifier.fit(X_train_ns,y_train_ns)

### Observation
 Over Sampeling performs well

## 2. SMOTE Tomek

This will create new points based on near points for low class.
Process is high compared to oversampeling.

In [49]:
from imblearn.combine import SMOTETomek

ImportError: cannot import name '_MissingValues' from 'sklearn.utils._param_validation' (C:\Users\z004vc9h\AppData\Local\anaconda3\Lib\site-packages\sklearn\utils\_param_validation.py)

In [51]:
os=SMOTETomek(0.5)
X_train_ns,y_train_ns=os.fit(X_train,y_train)
print("the number of classes before fit {}".format(Counter(y_train)))
print("the number of classes after fit {}".format(Counter(y_train_ns)))
classifier=RandomForestClassifier()
classifier.fit(X_train_ns,y_train_ns)

NameError: name 'SMOTETomek' is not defined

## Ensemble techniques

In [ ]:
from imblearn.ensemble import EasyEnsembleClassifer

easy=EasyEnsembleClassifer()
easy.fit(X_train,y_train)
